services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    networks:
      - net_containers_test
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  net_containers_test:
    driver: bridge